# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: mbedos/mbed-os-env:stable
    steps:
      - checkout:
          path: sinppet/TESTS
      - run: |
          cd sinppet/TESTS
          python3 .circleci/repo_checks.py
      - run: mv sinppet/TESTS/mbed-os.lib .
      - run: git clone https://github.com/ARMmbed/mbed-os.git mbed-os
      - run: |
          mbed config root .
          mbed update
          mbed add https://github.com/c1728p9/AudioPlayer
          mbed add https://github.com/ARMmbed/mbed-nfc-m24sr
          mbed test --compile -m K64F -t GCC_ARM -n sinppet-* --app-config=sinppet/TESTS/test.json -v
